title: "Fariya Asghar"
tagline: "Data Analyst | Transforming Data into Actionable Insights"
url: "https://fariyaasghar.github.io"
baseurl: "/data-portfolio-site"
theme: jekyll-theme-chirpy

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .github
