# GitHub Pages specific settings
remote_theme: cotes2020/jekyll-theme-chirpy

# Override theme setting for GitHub Pages
theme: null

# Rest same as main config
title: "Fariya Asghar"
tagline: "Data Analyst | Transforming Data into Actionable Insights"
description: "Professional portfolio showcasing data analysis projects"
url: "https://fariyaasghar.github.io"
baseurl: "/data-portfolio-site"

tabs:
  - about
  - projects
  - contact
  - resume

author:
  name: "Fariya Asghar"
  avatar: "/assets/img/avatar.jpg"
  bio: "Data Analyst with expertise in Python, SQL, Tableau, and financial analytics"
  location: "Frankfurt, Germany"

social:
  email: "fasghar91@gmail.com"
  links:
    - https://github.com/fariyaasghar
    - https://www.linkedin.com/in/fariya-asghar
    - https://public.tableau.com/app/profile/fariya.asghar

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Fariya Asghar"
      comments: false
      toc: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - LICENSE

markdown: kramdown
highlighter: rouge
timezone: Europe/Berlin
lang: en
